### ISSUE TITLE
Consolidated View of Pop-Up Plot Fields

### ISSUE THREAD

**Issue by charliepascoe** [cedadev/c3s_434_ecde_page_text#10]
A table view of the pop-up plot texts for each indicator.

**Comment by charliepascoe** [comment]
I've put the information for these in the PUPlotsConsol tab.

**Comment by charliepascoe** [comment]
MARIS (who are using this info) would like to have the text in json format.
Given that the tables in the google sheet are nice to look at I don't think it is necessary to reformat them into markdown format.

**Comment by charliepascoe** [comment]
But now that I see the tables with the consolidated text I can see that it was totally worth the effort!!

**Comment by jhaigh0** [comment]
@charliepascoe Sorry I need a quick reminder. Was this table going at the bottom of the markdown file with the same indicator value? e.g after the Explore section?

**Comment by charliepascoe** [comment]
Yes, the plan was to add the tables of pop up plot texts at the end of the consolidated text - after the table for the explore filters.

**Comment by jhaigh0** [comment]
In some cases there is data under for a table called 'NUTSClimatologyPlot', in those cases I'm going to assume there should be a second table after the pop up plot one. I'll make a new set of markdown files now and you can tell me what should change.

**Comment by charliepascoe** [comment]
Yes that's right, not all of the indicators have a climatology plot.  Thanks for all this, it looks great.

**Comment by charliepascoe** [comment]
It looks like the pop up plot title isn't processing anything beyond the first of the angled brackets.

**Comment by charliepascoe** [comment]
I think we should name these tables in the consolidated markdown text.
NUTS Pop Up Plot
NUTS Climatology Plot
