### ISSUE TITLE
Typo in BEDD title: Biologially

### ISSUE THREAD

**Issue by sharppaul** [cedadev/c3s_434_ecde_page_text#15]
In content/json/Consolidated.json:

Line 52:
```json
        "PageTitle": "Biologially effective degree days",
```

This causes all the markdown titles (and filenames) to be wrong. 

Also, another problem I'm having with these JSON files is that there's no consistent identifier for the texts, we could use the C3S Toolbox App identifier: e.g. hidden-app-agriculture-bedd-overview-web

At Maris we're currently trying to use these JSON files to for example load the texts for the static site [c3s.maris.nl](https://c3s.maris.nl), without a clear consistent identifier this is a harder task. (title's and descriptions can change, identifiers not really)

I hope this is the right location for this topic, otherwise please point me to the correct place to discuss this.

Greetings,

Paul Weerheim
Maris B.V.

**Comment by jhaigh0** [comment]
Hi @sharppaul 

I've fixed the typo for you.

On the topic of consistent identifiers, it would be best to talk to @charliepascoe, hopefully she can leave a comment here for you.

Best,
Jonathan Haigh

**Comment by sharppaul** [comment]
Hi @jhaigh0,

Thanks for the typo fix.

I think the consistent Identifier is already being picked up, as I mentioned it last week in a meeting and it was included in the notes.

Greetings,

Paul Weerheim, Maris B.V.

**Comment by charliepascoe** [comment]
I've started a new issue for json identifiers
https://github.com/cedadev/c3s_434_ecde_page_text/issues/16
