### ISSUE TITLE
Get code reading Charlotte's spreadsheet

### ISSUE THREAD

**Issue by agstephens** [cedadev/c3s_434_ecde_page_text#2]
The spreadsheet is:

https://docs.google.com/spreadsheets/d/1BHVHR1-3DC-AJ1ZQUtGUOs25fiGrt0adwmZcSNDFMk0/edit#gid=1104920491

Initially, you should be able to modify the existing code and tell it to read that spreadsheet instead of the "UKCP18 Datasets" spreadsheet that it is hard-coded to look at.

Don't forget to read the README! ;-)

**Comment by charliepascoe** [comment]
Suggest using "Climatic suitability for the tiger mosquito - season length" as a test case.
It's is on row 2 of the spreadsheet and looks like this on the ECDE portal:
https://c3s.maris.nl/health/climatic-suitability-of-tiger-mosquito--season-length.html

**Comment by agstephens** [comment]
Hi @charliepascoe and @jhaigh0 , I think the code should just batch process them all in the same way. But it will be good to have that as a comparison. 👍

**Comment by agstephens** [comment]
This is working.

**Comment by charliepascoe** [comment]
Note, I added a "PageTitle" column to the "Consolidated" tab.
