### ISSUE TITLE
Heatwaves in Europe index has wrong page text

### ISSUE THREAD

**Issue by charliepascoe** [cedadev/c3s_434_ecde_page_text#24]
@sharppaul
I think there is a mis-match between the page text for the heatwaves in Europe index and the data that are displayed.  https://c3s.maris.nl/health/heat-waves-and-cold-spells-in-europe.html

I notice that there is no option to choose a heatwave index (Health or Climate) for the data visualisation, which suggests to me that the data being displayed are either stats for the health-related heatwave or for the climatological heatwave.

In terms of page text:
Heatwaves in Europe is C3S_434_006
Health heatwave is C3S_434_016
Climate heatwave is C3S_434_017

**Comment by sharppaul** [comment]
Hi @charliepascoe 

I made some adjustments:

[https://c3s.maris.nl/health.html](https://c3s.maris.nl/health.html)
[https://c3s.maris.nl/energy.html (currently inaccessible from the c3s.maris.nl homepage)](https://c3s.maris.nl/energy.html)

However I thought the index/indicator URL wasn't really correct now, and changed it from:

- heat-waves-and-cold-spells-in-europe.html

to:

- health-heat-waves-in-europe

which is consistent with:

- climatological-heat-waves-in-europe-detail

**Comment by sharppaul** [comment]
Also I'm still confused as there are currently 3 heatwave texts, however there are only two indicators? (climatological definition and health definition)

**Comment by charliepascoe** [comment]
Hi @sharppaul I agree, those urls are better.
Sorry for the confusion re the 3 heatwave texts, I created 2 new indices for the separate health and climatological heat waves.
I'll remove the old heatwave text from the github repo but for now you can ignore it.
