### ISSUE TITLE
New Index: Fire Weather Index

### ISSUE THREAD

**Issue by charliepascoe** [cedadev/c3s_434_ecde_page_text#32]
A new fire weather index which will be available soon

**Comment by charliepascoe** [comment]
Managed by Johnny

**Comment by charliepascoe** [comment]
I think that the calculation for this index is essentially the same as for the existing fire weather index.
The difference is that this dataset contains future projections of the fire weather index and that the data is presented in terms of the number of days per year (season?) when the fire weather index exceeds a specific danger threshold.

**Comment by charliepascoe** [comment]
From @martinjuckes email:
We are dropping the "Fire Danger Index" from cems-fire-historical , which is based on the Australian system, to concentrate on the fire weather index from Canadian system which has been adopted for use in Europe.

The index from sis-tourism-fire-danger-indicators should use the "Number of days with high fire danger" and show an anomaly of the annual values in the scenario runs relative to 1986-2005 in the historical period. This uses the same risk evaluation system as the cems-fire-historical "Fire weather index" (https://c3s.maris.nl/forestry/fire-weather-indices.html ) , which we want to keep.

The use of "weather" versus "danger" in the names is arbitrary and confusing .. they are just different approaches to estimating the risk of forest fire.

**Comment by charliepascoe** [comment]
@rolle001
What threshold value of fire weather index are we using to calculate the number of days with high fire danger?
and
What time periods are we presenting the data for?  Month, Season, Year?

**Comment by charliepascoe** [comment]
@rolle001 
You can ignore that last lot of questions, I found the answer here https://cds.climate.copernicus.eu/cdsapp#!/dataset/sis-tourism-fire-danger-indicators?tab=overview

**Comment by charliepascoe** [comment]
Markdown content https://github.com/cedadev/c3s_434_ecde_page_text/blob/main/content/markdown/consolidated/High_Fire_Danger%2C_1970-2098.md

**Comment by charliepascoe** [comment]
@sharppaul The new high fire danger index is in the latest update to the Consolidated.json https://github.com/cedadev/c3s_434_ecde_page_text/blob/main/content/json/Consolidated.json

**Comment by sharppaul** [comment]
Hi @charliepascoe 

I'm getting a bit confused as to which index should be replaced by these texts. 
I assume its FireDangerIndex: https://c3s.maris.nl/forestry/fire-danger-indices.html (C3S_434_005)

My confusion is about whether or not this is already the correct Toolbox app, since I updated this one last week with.

Maybe @rolle001 can confirm or deny that. Since if that's the case, the Toolbox app only has options for years 1979-2019, and not 1970-2098.

Cheers,

**Comment by charliepascoe** [comment]
*sharppaul
The old "fire weather index" and "fire danger index" were historical indices from 1979-2019.
As far as I understand, neither of these are going to be included in the next release.

The new "high fire danger" index has a historical portion and future projections, the [CDS page](https://cds.climate.copernicus.eu/cdsapp#!/dataset/sis-tourism-fire-danger-indicators?tab=overview 
) about this dataset says it goes from 1970-2098 so I used that to build the index name but I might need to change the time range when I see how it gets implemented in the maris portal

**Comment by sharppaul** [comment]
Alright, this cleared up some of my confusion.

I updated the Maris portal:
  https://c3s.maris.nl/forestry
  https://c3s.maris.nl/forestry/high-fire-danger.html
  https://c3s.maris.nl/forestry/high-fire-danger-detail.html

**Comment by charliepascoe** [comment]
@sharppaul can you add the high fire danger index to the tourism sector as well.

**Comment by charliepascoe** [comment]
At progress meeting this morning we decided to adjust the title of this index to include "Fire Weather Index".
We are also going to keep the historical fire weather index so we also need to make it clear in the title that the historical index is monthly mean data and the projected index is days above the danger threshold.

**Comment by charliepascoe** [comment]
These updates have been implemented in the demo portal
