### ISSUE TITLE
New Index: Snow Depth

### ISSUE THREAD

**Issue by charliepascoe** [cedadev/c3s_434_ecde_page_text#33]
Snow depth to be presented at NUTS 3 only

**Comment by charliepascoe** [comment]
Managed by Rutger

**Comment by charliepascoe** [comment]
User can select elevation band, climate scenario and time period.
Plan is to show anomalies for snow depth.
Second plot content is usually an annual climatology but it is not clear exactly what this will show as we only have annual data for snow.

**Comment by charliepascoe** [comment]
note there are 2 snow indices

**Comment by charliepascoe** [comment]
Tourism Sector

**Comment by charliepascoe** [comment]
Info from @RutgerDankers
There is a preliminary version of the detailed view app for the snow indicators: https://cds.climate.copernicus.eu/toolbox-editor/ecde/c3s_434_tourism_snow_detail It is preliminary because I am waiting for a solution from James to prevent the user from clicking on regions with no snow data for the chosen elevation band. I do have an alternative solution (currently implemented), which will show a message to the user when they click on such a region, so if James is not able to fix the errors that I am getting with his method, we can go for this alternative solution.

The dataset is 'sis-tourism-snow-indicators' and the variables used are 'total_snow_precipitation_from_november_to_april' (kg m-2) and 'period_with_high_amount_of_natural_snow' (days).

The data are provided on NUTS-3 regions only, for a range of elevation bands. Obviously, not every elevation band is available at every region (hence the need for appropriate error handling).

Data are provided for a range of GCM/RCM combinations, and the workflow retrieves all (except for one combination that uses a different calendar and is therefore causing errors; this one is currently skipped). In addition there is a reanalysis dataset obtained from UERRA.

Similar to before, anomalies are calculated for each region and elevation band by comparing data from the historical runs with the scenarios. For the total snow precipitation the anomalies shown are relative anomalies, for the number of days with high amount of snow, absolute anomalies are shown. The anomalies are then averaged across the ensemble models and the min/max across the ensemble is determined.

The data are shown on a livemap for the chosen time period, RCP and elevation band. When clicking on a region with data for the selected elevation, a timeseries plot of anomalies is chosen with anomalies for the entire century. In addition a plot is shown showing the UERRA reanalysis data as absolute values, not as a climatology plot (as in other apps), but as a timeseries because we are dealing with annual data.

I think the same workflow can be used to show the two indicators on two different pages (as before), in which case the indicator dropdown menu would be hidden.

BTW the colour scale may need changing as well, this also depends on whether or not James can find a solution for the no data regions.

@Paul Weerheim if James cannot fix the errors in time, the current workflow will be the version to be published. Perhaps you could already check the layout of the figures, etc. Please also check what happens when a user clicks on a no-data region (essentially some blank plots are returned) and how this would show in the portal.

**Comment by charliepascoe** [comment]
The snow indices are in the Maris portal, this is great because I can see what the dropdown menus will be.

https://c3s.maris.nl/tourism/tourism-high-amount-of-natural-snow.html
https://c3s.maris.nl/tourism/tourism-snow-precipitation.html

**Comment by sharppaul** [comment]
As a comment: The 'Indicator' dropdown will/should be hidden when it's being published.

**Comment by charliepascoe** [comment]
@sharppaul the json has been updated to include page text for these snow indices:
C3S_434_021 Total Winter Snow
C3S_434_022 High Snowfall Days

**Comment by sharppaul** [comment]
I updated the portal to include these texts:
https://c3s.maris.nl/tourism.html 
https://c3s.maris.nl/tourism/tourism-high-amount-of-natural-snow.html
https://c3s.maris.nl/tourism/tourism-snow-precipitation.html

The workflows will be updated over the weekend to work correctly. There'll also be a correct overview workflow available, which consists of a dumbed down detail workflow to show data at the correct NUTS level.
