### ISSUE TITLE
New Index: Mean Sea Level

### ISSUE THREAD

**Issue by charliepascoe** [cedadev/c3s_434_ecde_page_text#34]
Coastal index

**Comment by charliepascoe** [comment]
Managed by Rutger

**Comment by charliepascoe** [comment]
Marine Sector

**Comment by charliepascoe** [comment]
Info from @RutgerDankers
The link to the Toolbox apps for the sea level indicators can be found below. Once James has published them they will be included in the MARIS portal (hopefully soon).

The dataset used is 'sis-water-level-change-indicators' or https://cds.climate.copernicus.eu/cdsapp#!/dataset/sis-water-level-change-indicators?tab=overview

The variables included are 'annual_highest_high_water_level' and 'mean_sea_level'.

Data are only shown for RCP4.5 covering the period 2071-2100, since RCP8.5 only covers 2041-2070.

The data are shown as anomalies from the historical experiment, which for this dataset covers 1977 to 2005.

The original data are on irregularly spaced points, these have been averaged over the marine regions shown. Note the anomalies were calculated first, so these were first calculated at the model points, and the anomalies were then averaged over the region.

**Comment by charliepascoe** [comment]
Info from @sharppaul 
The following Sealevel indices/apps are online in the MARIS portal under the “Energy” theme, which I don’t think is correct, but it’s a temporary place for now.

Annual highest high water level:
https://c3s.maris.nl/energy/marine-sea-level--annual-highest-high-water-level.html
https://c3s.maris.nl/energy/marine-sea-level--annual-highest-high-water-level-detail.html

Mean sea level:
https://c3s.maris.nl/energy/marine-sea-level--mean-sea-level.html
https://c3s.maris.nl/energy/marine-sea-level--mean-sea-level-detail.html

These currently do not work yet, they might work tomorrow. It depends on how fast the toolbox propagates the workflows to production. (According to @'James Varndell')

I hope to receive more clarity regarding the theme from you.
As well for the other energy index/indicator: Climatological Heatwave, since it doesn’t feel right having it under this theme, as it’s the only one there.

**Comment by charliepascoe** [comment]
I've been reading the sea level dataset [user guide](http://datastore.copernicus-climate.eu/documents/sis-european-coasts/Product_user_guide_sea_level_wave_v4_final.pdf).  It seems that the use of different time periods: RCP8.5 for 2040-2070 and RCP4.5 for 2070-2100 is intentional and is intended to reflect a world in which greenhouse gas emissions are not reduced until the mid 21st century. So for the purposes of this dataset we should include both RCPs.

**Comment by charliepascoe** [comment]
@RutgerDankers can you remind me, will we be showing...
the variable resolution model output on the landing page and marine region averages on the explore page
or the marine region averages on both the landing page and the explore page?

**Comment by charliepascoe** [comment]
@RutgerDankers where can I find information about the marine regions we have used?

**Comment by charliepascoe** [comment]
I have gathered information about the sea level indices to generate most of the text on the main page of these indices.  Just waiting on info about he drop-down boxes.  Unfortunately the [toolbox-editor view](https://cds.climate.copernicus.eu/toolbox-editor/ecde/c3s_434_marine_sealevel_overview) is not working for me.

**Comment by charliepascoe** [comment]
@sharppaul and @RutgerDankers
I have created json page text for the two sea level indices: annual highest high water C3S_434_018 and mean sea level C3S_434_019.
Note that I don't yet have information about the coastal marine areas so those are not described in the text.
I have assumed that we won't present the users with dropdown boxes because we're only giving the users the option to view the 2070-2100 RCP4.5 data at this time, but I have text that is ready to use when we do.

The thing that I had to understand about this dataset is that we should think of the different sections in terms of the time period they cover rather than the CMIP5 scenario they use.

- 1977-2005: ERA5: historical data
- 2040-2070: RCP8.5: near future with high GHG forcing
- 2070-2100: RCP4.5: far future with medium GHG forcing

In the dropdown menus we should offer the user the choice of different time periods that happen to have different forcings.

**Comment by sharppaul** [comment]
The coastal indicators now have their own sector/theme:
[https://c3s.maris.nl/coastal.html](https://c3s.maris.nl/coastal.html)

The sector still needs a description as mentioned in #49 

The indicators have moved here, their new URLs are:
[https://c3s.maris.nl/coastal/marine-sea-level--annual-highest-high-water-level.html](https://c3s.maris.nl/coastal/marine-sea-level--annual-highest-high-water-level.html)
[https://c3s.maris.nl/coastal/marine-sea-level--mean-sea-level.html](https://c3s.maris.nl/coastal/marine-sea-level--mean-sea-level.html)

**Comment by charliepascoe** [comment]
Martin raised an issue to make it clear that sea level rise is relative to mean sea level and not relative to land. #50
