### ISSUE TITLE
Update text for NUTS drop down menu titles

### ISSUE THREAD

**Issue by charliepascoe** [cedadev/c3s_434_ecde_page_text#35]
NUTS-level needs more generic regional definition as trans-national Europe-wide means are also provided.

**Comment by martinjuckes** [comment]
Replace labels in drop-down (all workflows, explorer view) ("0", "1", "2") with:

- National level (NUTS0)
- First sub-national level (NUTS1)
- Second sub-national level (NUTS2)

See https://docs.google.com/document/d/1nXKpzqvI2Ig_cO0gXMpQLH1rXFg7VIo_/edit

**Comment by charliepascoe** [comment]
18 Selection of regional aggregation: 
The following options should be provided for the selection of regional aggregation units: 
EEA member and cooperating countries (EEA-38)
National level (NUTS0)
First sub-national level (NUTS1)
Second sub-national level (NUTS2)
Original resolution (e.g. raster)
Europe → "Europe (EEA 38)" in pop-up.  (implement in workflows); also NUTS 0-2; raster view not currently mixed with region view.

**Comment by charliepascoe** [comment]
Done in the page text and in the filter text.
