### ISSUE TITLE
Mosquito Season Length and suitability - link and definition

### ISSUE THREAD

**Issue by martinjuckes** [cedadev/c3s_434_ecde_page_text#37]
The Climate Data Store link goes to the wrong dataset on both pages .. it should go to https://cds.climate.copernicus.eu/cdsapp#!/dataset/sis-health-vector?tab=doc 

The season length is defined in terms of temperature and hours of sunlight: rainfall affects the suitability, but not the season length (see [documentation](https://datastore.copernicus-climate.eu/documents/sis-european-health/Vectors_extra_documentation.pdf)).

The suitability is defined in terms of both temperature and rainfall (the current text refers to rainfall only).

**Comment by charliepascoe** [comment]
Fixed links and updated the definitions.
