### ISSUE TITLE
Health Heatwave (High Temperature and Humidity) 

### ISSUE THREAD

**Issue by martinjuckes** [cedadev/c3s_434_ecde_page_text#39]
The page text refers to "A health-related heatwave is a prolonged period of extremely high temperature and humidity for a particular region that exceeds both maximum and minimum thresholds" -- I think this is unclear. The definition given in the documentation refers to daily minima and maxima both exceeding thresholds. Perhaps: "A health-related heatwave is a prolonged period of extremely high temperature and humidity for a particular region during which daily minima and maxima both exceed thresholds" 

https://c3s.maris.nl/health/health-heat-waves-in-europe.html

**Comment by charliepascoe** [comment]
Done
