### ISSUE TITLE
Replace use of anomaly

### ISSUE THREAD

**Issue by charliepascoe** [cedadev/c3s_434_ecde_page_text#41]
Hans-Martin:
I propose to use the following replacements:
a.	for indices based on observations and reanalysis: “Observed change”; 
b.	for indices based on projections (only): “Projected change”;
c.	for indices based on hindcasts and projections, I propose replacing by “Modelled past and projected change”.

**Comment by charliepascoe** [comment]
This is same as issue #42

**Comment by sharppaul** [comment]
@charliepascoe I'm currently reviewing the Toolbox indicator apps/workflows, they usually contain the word anomaly in options like:

**Anomaly period**
_Choose an anomaly period_

Any suggestion for what to change it to?
