### ISSUE TITLE
Sector for Climate heatwave

### ISSUE THREAD

**Issue by charliepascoe** [cedadev/c3s_434_ecde_page_text#47]
@sharppaul writes
"energy index/indicator: Climatological Heatwave, it doesn’t feel right having it under this theme, as it’s the only one there."

**Comment by charliepascoe** [comment]
@sharppaul I think it is ok for the climatological heatwave index to be in the energy sector, heatwaves place a greater demand on air conditioning.

But we should add climatological heatwave to the agriculture sector too.

**Comment by charliepascoe** [comment]
@sharppaul please can you add the climatological heatwave to the agriculture sector (as well as the energy sector).

**Comment by sharppaul** [comment]
Hi @charliepascoe, I just got to this now. Is this still required?

**Comment by charliepascoe** [comment]
@sharppaul I think we should place this on hold for now and have a discussion with Hans-Martin about placing indices in multiple sectors.

**Comment by charliepascoe** [comment]
I am not exactly sure.
I raised the issue of indices being in multiple sectors it in a meeting with H-M but the discussion wasn't conclusive.
I think we've should hold off doing this for now (but I don't think we should worry if you've already done it) and raise it as an agenda item at the progress meeting.
Charlotte
________________________________
