### ISSUE TITLE
Sectors for Indicators

### ISSUE THREAD

**Issue by charliepascoe** [cedadev/c3s_434_ecde_page_text#48]
@sharppaul needs to know the sectors that each indicator is associated with.

**Comment by charliepascoe** [comment]
For the moment I'm listing the sectors that each index is associated with on my spreadsheet:
Columns B, C, and D of the MainElements tab https://docs.google.com/spreadsheets/d/1BHVHR1-3DC-AJ1ZQUtGUOs25fiGrt0adwmZcSNDFMk0/edit#gid=0

See also #19

**Comment by charliepascoe** [comment]
Need to make sure this info is passed through to the json

**Comment by sharppaul** [comment]
Hi @charliepascoe 

The info doesn't necessarily have to be in the JSON, since I adjust sectors mostly by hand anyway. Texts and titles in the JSON since they change the most.
