### ISSUE TITLE
New sectors need short description 

### ISSUE THREAD

**Issue by charliepascoe** [cedadev/c3s_434_ecde_page_text#49]
The new sectors, tourism and coastal, need some text for their landing pages.

**Comment by sharppaul** [comment]
New sector URLs:
[Coastal](https://c3s.maris.nl/coastal.html)
[Tourism](https://c3s.maris.nl/tourism.html)

**Comment by sharppaul** [comment]
They also need images for the [main overview page](https://c3s.maris.nl/).

**Comment by sharppaul** [comment]
I updated the Maris portal:

https://c3s.maris.nl/tourism.html
https://c3s.maris.nl/coastal.html

Was wondering if the sources should be included aswell?

**Comment by charliepascoe** [comment]
High Fire Danger is also a tourism index so we should include wildfire in the tourism sector description.  Here's my suggestion for an updated Tourism sector description.

Europe is the world's number one tourist destination and the warming climate has the potential to significantly affect the appeal of tourist destinations. Winter tourism faces increasing losses due to reduced snow cover and summer tourism faces increasing risks due to wildfire.
