### ISSUE TITLE
Generate Markdown versions of "Consolidated" worksheet

### ISSUE THREAD

**Issue by agstephens** [cedadev/c3s_434_ecde_page_text#6]
Create a very simple markdown file for each record under:
- `content/markdown/<worksheet_name>/<record_name>.md` - one per record

Create a title for the record, markdown formatted.

Push them to github and show @charliepascoe

**Comment by jhaigh0** [comment]
Finished this, md files are very simple and are only created for the consolidated texts currently. Will need to speak to @charliepascoe to discuss how they should look / what they should contain.
