### ISSUE TITLE
Mean Sea Level

### ISSUE THREAD

**Issue by charliepascoe** [cedadev/c3s_434_ecde_page_text#62]
This name should be changed to Mean Relative Sea Level

**Comment by charliepascoe** [comment]
This index is called "Mean Sea Level" in the CDS I don't agree that we should change it to Mean Relative Sea Level.
However, I have changed the order of the sentences in the description so that we highlight the fact that this is a relative change. I have made a similar change to the annual highest high water index too. 

The description now reads:
The projected change in mean sea level (m) is calculated relative to the mean of the mean sea level during the historical period from 1977-2005. Tidal dyamics and sea level rise data are taken into account in the calculation of this index. However, storm surges caused by atmospheric forcing, and coastal subsidence and/or uplifting are not taken into account for this index.

**Comment by charliepascoe** [comment]
json files have been updated https://github.com/cedadev/c3s_434_ecde_page_text/commit/863b170ae4015eb4bb6217899545d1d1442f4009

**Comment by charliepascoe** [comment]
Email Sam to find out if the CDS variable we're using is relative to historical sea level or relative to land.

**Comment by charliepascoe** [comment]
From Sam:
The Sea Level within this dataset is based on forcing from climate models and combined with relative sea level forcing - Therefore the result do not take into account local impacts related to geology (such as isostatic rebound or subsidence).

Relative SLR forcing is using the CMIP5 ensemble mean - The sea level rise corresponding to the two emission scenarios considered is forced through the ensemble-mean relative sea level rise fields (RSLR) in the Coupled Model Intercomparison Project Phase 5 (CMIP5). These fields are given as yearly fields for each emission scenario, up to 2100.’  

The SLR fields that the datasets used were taken from the IPCC. The contractor used the repository of the university of Hamburg: https://icdc.cen.uni-hamburg.de/en/ar5-slr.html where more information can be provided.

The inputs are 1°x1, and therefore no not take into account localised geological effects.

**Comment by charliepascoe** [comment]
From the ICDC dataset page:
These are the relative sea surface height (SSH) data, which was used in the construction of figures for the Fifth Assessment Report of the Intergovernmental Panel on Climate Change (IPCC-AR5). The data include 10 geophysical sources that drive long-term changes in relative SSH:

- 5 ice components (Greenland dynamic ice and surface mass balance, Antarctic dynamic ice and surface mass balance, and glaciers),
- 3 ocean-related components, all of which are derived from CMIP5 models (dynamic SSH, global thermosteric SSH anomaly, and the inverse barometer effect from the atmosphere),
- land water storage (also called terrestrial water),
- and glacial isostatic adjustment (as a change in sea level relative to land).

**Comment by charliepascoe** [comment]
New dataset link: https://www.cen.uni-hamburg.de/icdc/data/ocean/ar5-slr.html

**Comment by charliepascoe** [comment]
This variable is calculated relative to mean sea level change and not relative land, but it does take glacial isostatic adjustment into account via the forcing dataset used as input to the EC-EARTH model.
Therefore we do not need to change the name of the index.
However, we do need to explain that relative sea surface height has been used to force the outer "nest".

I have updated the "Definition" to remove the statement that says that coastal subsidence and uplift are not included. 
I have added text to the "Data Sources" section to describe the relative SSH forcing dataset used by EC-EARTH.

**Definition**
The projected change in mean sea level (m) is calculated relative to the mean of the mean sea level during the historical period from 1977-2005. 
Tidal dynamics, and sea level change data from climate models are taken into account in the calculation of this index. Storm surges caused by atmospheric forcing are not taken into account for this index.

**Data Sources**
The data covers the period from 2070 to 2100 based on CMIP5 scenario RCP4.5 with medium greenhouse gas emissions.
The index is generated using the Global Tide and Surge Model (GTSM, Deltares) and the Wave Model (WAM, ECMWF). High resolution forcing fields for the GTSM are provided by the Danish Meteorological Institute's regional model (HIRHAM5) which is downscaled from the EC-EARTH global climate model.
The EC-EARTH simulations used input from a relative Sea Surface Height (SSH) dataset that takes into account geophysical drivers of long-term SSH change, such as changes to the Greenland and Antarctic ice sheets, thermal expansion of the ocean, and glacial isostatic adjustment.
Given that the projections of these climate scenarios are based on a single combination of the regional and global climate models, users of these data should take into consideration that there is an inevitable underestimation of the uncertainty associated with this dataset.

**Comment by charliepascoe** [comment]
I have added "glacial isostatic adjustment" to the glosssary.

**Comment by charliepascoe** [comment]
Updated json https://github.com/cedadev/c3s_434_ecde_page_text/commit/ac1a507ae5ca451c9ef204cd1fd0c8714463586c

**Comment by charliepascoe** [comment]
@sharppaul I have updated the json for the two coastal indices and for the glossary.

**Comment by martinjuckes** [comment]
However, "glacial isostatic adjustment" is about movement of the land, and the dataset documentation makes several references to relative sea-level rise.

**Comment by charliepascoe** [comment]
At the progress meeting today we decided to call this index mean relative sea level.
The description should not that regional changes due to glacial isostatic adjustment are included but land changes due to local subsidence/uplift are not.

**Comment by charliepascoe** [comment]
https://github.com/cedadev/c3s_434_ecde_page_text/commit/c389d51fa0bf99cbb849d4875d58bc46b9df4749
Pushed changes to the json
@sharppaul for info
