### ISSUE TITLE
Remove newline characters from Consolidated work sheet

### ISSUE THREAD

**Issue by jhaigh0** [cedadev/c3s_434_ecde_page_text#7]
Currently in the Consolidated work sheet, cells C6-C13 are consolidating a lot of empty strings (since they're aren't that many entries yet). This leads to some newline characters being put in those cells but no actual information.
When downloading the data from the spread sheets these newline characters get put into the json array for consolidated texts, leaving a bunch of entries which look like this;

```json
{
    "ConsolidatedText_Explore": "    \n\n  \n\n \n\n\n\n \n\n\n\n  ",
    "ConsolidatedText_Main": "",
    "Indicator": ""
},
```

This currently creates some problems when creating the markdown files.
I think cells C6-C13 shouldn't have their consolidation function until there is actual data, to fix this problem.

**Comment by charliepascoe** [comment]
Sorry about that.  I've removed the concatenate function content from the empty cells on the consolidated tab.
