### ISSUE TITLE
Typo in daily mean temperature "suface" air temperature.

### ISSUE THREAD

**Issue by sharppaul** [cedadev/c3s_434_ecde_page_text#74]
Hi Charlotte, Sylvia found a typo on the following page:

https://climate-adapt.eea.europa.eu/metadata/indicators/daily-mean-temperature-monthly-mean-2011-2099 

"Projected change in monthly and seasonal statistics of daily mean 2m **_suface_** air temperature"

**Comment by charliepascoe** [comment]
Thanks @sharppaul I've corrected the typo in the json files.
